create table categories
(
    id        bigserial
        primary key,
    name      varchar(100) not null,
    parent_id bigint
                           references categories
                               on delete set null,
    constraint uq_category_parent_name
        unique (parent_id, name)
);

alter table categories
    owner to admin;

create table otp_codes
(
    id         bigserial
        primary key,
    email      varchar(255) not null,
    otp        varchar(255) not null,
    expires_at timestamp    not null,
    verified   boolean default false
);

alter table otp_codes
    owner to admin;

create table users
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6),
    email      varchar(100) not null
        constraint uk6dotkott2kjsp8vw4d0m25fb7
            unique,
    is_active  boolean,
    name       varchar(255) not null,
    password   varchar(255) not null,
    phone      varchar(255),
    surname    varchar(255) not null,
    user_role  varchar(20)  not null
        constraint users_user_role_check
            check ((user_role)::text = ANY
        ((ARRAY ['CUSTOMER'::character varying, 'OWNER'::character varying, 'ADMIN'::character varying])::text[])),
    deleted    boolean
);

alter table users
    owner to admin;

create table products
(
    id           bigserial
        primary key,
    category_id  bigint
        constraint fk_products_category
            references categories
            on delete set null,
    name         varchar(150)           not null,
    description  text,
    price        numeric(38, 2)         not null,
    created_at   timestamp default CURRENT_TIMESTAMP,
    owner_id     bigint
        constraint fkmodgy1j6kai83i3mweyp731qc
            references users,
    is_available boolean   default true not null
);

alter table products
    owner to admin;

create table product_images
(
    id         bigserial
        primary key,
    product_id bigint       not null
        constraint fk_product_images_product
            references products
            on delete cascade,
    image_url  varchar(255) not null
);

alter table product_images
    owner to admin;

create table orders
(
    id            bigserial
        primary key,
    order_date    timestamp   default CURRENT_TIMESTAMP,
    order_status  varchar(20) default 'PENDING'::character varying
        constraint orders_order_status_check
            check ((order_status)::text = ANY
                   ((ARRAY ['CREATED'::character varying, 'PENDING'::character varying, 'PAID'::character varying, 'DELIVERED'::character varying, 'RETURNED'::character varying, 'CANCELLED'::character varying])::text[])),
    customer_id   bigint
        constraint fksjfs85qf6vmcurlx43cnc16gy
            references users,
    day           integer,
    total_amount  numeric(38, 2),
    product_id    bigint
        constraint fkkp5k52qtiygd8jkag4hayd0qg
            references products
            on delete set null,
    delivery_type varchar(255)
        constraint orders_delivery_type_check
            check ((delivery_type)::text = ANY
        ((ARRAY ['DELIVERY'::character varying, 'PICKUP'::character varying])::text[]))
    );

alter table orders
    owner to admin;

create unique index unique_created_order_per_customer
    on orders (customer_id)
    where ((order_status)::text = 'CREATED'::text);

create table payments
(
    id             bigserial
        primary key,
    order_id       bigint
        constraint fk_payments_order
            references orders,
    users_id       bigint
        constraint fke9hmevvy1ubu67yeyu73yw2ri
            references users,
    amount         numeric(10, 2) not null,
    payment_date   timestamp   default CURRENT_TIMESTAMP,
    payment_method varchar(20) default 'CARD'::character varying
        constraint payments_payment_method_check
            check ((payment_method)::text = ANY
                   ((ARRAY ['CARD'::character varying, 'CASH'::character varying])::text[])),
    status         varchar(20) default 'PENDING'::character varying
        constraint payments_status_check
            check ((status)::text = ANY
                   ((ARRAY ['SUCCESS'::character varying, 'FAILED'::character varying, 'PENDING'::character varying])::text[])),
    expire_date    varchar(7),
    purpose        varchar(255),
    card_number    varchar(4),
    cvv            varchar(3)
);

alter table payments
    owner to admin;

create table favorites
(
    id          bigserial
        primary key,
    product_id  bigint not null
        constraint fk_favorites_product
            references products,
    created_at  timestamp default CURRENT_TIMESTAMP,
    customer_id bigint
        constraint fk56bvektuw7xi7dgfqyd9kcdh2
            references users
);

alter table favorites
    owner to admin;

create table product_reviews
(
    id          bigserial
        primary key,
    product_id  bigint not null
        constraint fk_reviews_product
            references products
            on delete cascade,
    comment     text,
    created_at  timestamp default CURRENT_TIMESTAMP,
    customer_id bigint not null
        constraint fkhmbqmkl8r398rwsrwhv4urr1a
            references users
);

alter table product_reviews
    owner to admin;

create table refresh_tokens
(
    id          bigserial
        primary key,
    expiry_date timestamp    not null,
    revoked     boolean default false,
    token       varchar(500) not null
        unique,
    user_id     bigint       not null
        constraint fk1lih5y2npsf8u5o3vhdb9y0os
            references users
);

alter table refresh_tokens
    owner to admin;

create table addresses
(
    id      bigint generated by default as identity
        primary key,
    city    varchar(100) not null,
    home    varchar(50)  not null,
    street  varchar(150) not null,
    user_id bigint       not null
        constraint fk1fa36y2oqhao3wgg2rw1pi459
            references users
);

alter table addresses
    owner to admin;

